In [1]:
import numpy as np

In [4]:
# Write a NumPy program that creates a 2D NumPy array of random integers. Use boolean indexing to select all elements greater than a specified value.

arr = np.random.randint(1,100,100).reshape(2,50)

print("Original Array: \n", arr)

value = 50
arr[ arr > value]

Original Array: 
 [[ 3 11 86 17 85 50 61 79 25 51 81 29 69 40 90 90 62  7 67 89 76 82 55 11
  38 94  8 68 36 96 38 94 13  5 19  8 34 14 69 97 49 13 76 60 38 27 31 87
   8 87]
 [35 84 48 93 23 97 69 20 64 96 63 49 50  2 37 94 51 74 53 20  5  8 30 50
  34 48 41 38 40 93 68 30 15 99 45 68 93 28 59 38 78 80 99 37 25 85 62 91
  81 18]]


array([86, 85, 61, 79, 51, 81, 69, 90, 90, 62, 67, 89, 76, 82, 55, 94, 68,
       96, 94, 69, 97, 76, 60, 87, 87, 84, 93, 97, 69, 64, 96, 63, 94, 51,
       74, 53, 93, 68, 99, 68, 93, 59, 78, 80, 99, 85, 62, 91, 81])

In [6]:
# Write a NumPy program that creates a 1D NumPy array and uses integer array indexing to select a subset of elements based on an index array.

arr = np.random.randint(1,100,10)

print("Original Array: ", arr)
arr[:5]

Original Array:  [86 76 79 35 58 13 29 91 19 10]


array([86, 76, 79, 35, 58])

In [7]:
# Write a NumPy program that creates a 2D NumPy array and uses a mask array (boolean array) for indexing to select a subset of elements that match the mask criteria.
arr = np.random.randint(1,100,10)

print("Original Array: \n", arr)

value = 50

mask = arr > value
arr[mask]

Original Array: 
 [44 20 40 99 78 39  3 76 89 53]


array([99, 78, 76, 89, 53])

In [8]:
# Write a NumPy program that creates a 5D NumPy array. Use boolean indexing to select elements along specific dimensions based on conditions applied to other dimensions.

array_5d = np.random.randint(0, 100, size=(3, 4, 2, 3, 5))

print(array_5d)
condition = array_5d > 50

array_5d[condition]

[[[[[97 90 10 74 47]
    [62 62 37 17 53]
    [40 89 59 57 73]]

   [[31 48 97 59 69]
    [10 62 72 56 66]
    [ 0 68 71 68 74]]]


  [[[80 74 77 18 14]
    [ 9 24  9 54 83]
    [60 77 95 31 14]]

   [[48 24 65 29 17]
    [32  5 71 64 38]
    [12 70 22 83 23]]]


  [[[74 83 35 81 36]
    [56 93 22 60 86]
    [ 7 58 96 54 32]]

   [[62 71 46 24 98]
    [42 75  0 53 13]
    [19  7 80 91 38]]]


  [[[91  3 29  1 65]
    [70 57  5 17 71]
    [38 86 26 64 63]]

   [[24 97 46 76 98]
    [21 67 97 17  9]
    [63 76 67 68  2]]]]



 [[[[61 65 55 17 85]
    [45 97 31 74 26]
    [33 39 78 46 34]]

   [[59 54 49 40 16]
    [63 39 20 13 76]
    [75 13 42 36 57]]]


  [[[40 79 33 68 77]
    [85 42 95 22 38]
    [41 37 75 26 18]]

   [[65 73 21 50  9]
    [48 56 77 47 25]
    [79 90 95  6 33]]]


  [[[12 84 96 53 89]
    [45 95  5 20 13]
    [13 76 79 23 82]]

   [[67 66 47 51 36]
    [ 5  3 75 71 80]
    [82 49 17 38 22]]]


  [[[34 58 45 48 47]
    [76 74  2 71 40]
    [22 43 93 52 18]]

   [[44 4

array([97, 90, 74, 62, 62, 53, 89, 59, 57, 73, 97, 59, 69, 62, 72, 56, 66,
       68, 71, 68, 74, 80, 74, 77, 54, 83, 60, 77, 95, 65, 71, 64, 70, 83,
       74, 83, 81, 56, 93, 60, 86, 58, 96, 54, 62, 71, 98, 75, 53, 80, 91,
       91, 65, 70, 57, 71, 86, 64, 63, 97, 76, 98, 67, 97, 63, 76, 67, 68,
       61, 65, 55, 85, 97, 74, 78, 59, 54, 63, 76, 75, 57, 79, 68, 77, 85,
       95, 75, 65, 73, 56, 77, 79, 90, 95, 84, 96, 53, 89, 95, 76, 79, 82,
       67, 66, 51, 75, 71, 80, 82, 58, 76, 74, 71, 93, 52, 95, 66, 89, 81,
       58, 84, 84, 68, 60, 55, 94, 57, 63, 86, 74, 63, 51, 56, 56, 64, 59,
       66, 94, 73, 87, 57, 79, 78, 73, 51, 75, 91, 78, 76, 58, 55, 90, 53,
       66, 55, 72, 85, 51, 63, 73, 64, 57, 84, 78, 74, 96, 53, 53, 99, 95,
       94, 82, 63, 68, 88, 98, 58, 92, 89, 99, 86, 81])