In [1]:
import numpy as np

In [7]:
# Write a NumPy program to sort an given array by the nth column.
# Original array:
# [[1 5 0]
# [3 2 5]
# [8 7 6]]
# Sort the said array by the nth column:
# [[3 2 5]
# [1 5 0]
# [8 7 6]]

arr = np.array([[1,5,0],[3,2,5],[8,7,6]])
print("Original Array: \n", arr)

n = 1

arr[arr[:,n].argsort()]

Original Array: 
 [[1 5 0]
 [3 2 5]
 [8 7 6]]


array([[3, 2, 5],
       [1, 5, 0],
       [8, 7, 6]])

In [12]:
# Write a  NumPy program to sort the specified number of elements from beginning of a given array.
# Sample output:
# Original array:
# [0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]
# Sorted first 5 elements:
# [0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]

# Creating an array of 10 random numbers
nums = np.random.rand(10)

# Displaying the original array
print("Original array:")
print(nums)

# Sorting the first 5 elements using argpartition
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums, range(5))]) 


Original array:
[0.62149194 0.13209619 0.27833241 0.92660933 0.27990662 0.60137262
 0.70987933 0.79137517 0.72227555 0.18773482]

Sorted first 5 elements:
[0.13209619 0.18773482 0.27833241 0.27990662 0.60137262 0.92660933
 0.70987933 0.79137517 0.72227555 0.62149194]


In [14]:
#  Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.
# Expected Output:
# Original array:
# [(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]
# Sort by age, then height if class are equal:
# [(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 ) (b'Nail', 6, 52.5 )]

# Defining the data types for the structured array
data_type = [('name', 'S15'), ('class', int), ('height', float)]

# Defining the details of students as a list of tuples
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

# Creating a structured array 'students' using the defined data type and provided details
students = np.array(students_details, dtype=data_type)

np.sort(students, order=['class', 'height'])

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])