In [1]:
import numpy as np

In [2]:
# Create a 2D array with random integers and replace all values greater than a certain threshold with that threshold.

arr = np.random.randint(1,10,20).reshape(4,5)

print("original array: \n", arr)

threshold_value = 5

condition = arr > threshold_value

arr[condition] = threshold_value

print("After setting the threshold value: \n", arr)

original array: 
 [[9 1 8 3 1]
 [8 1 6 8 5]
 [5 7 3 8 9]
 [8 2 8 3 5]]
After setting the threshold value: 
 [[5 1 5 3 1]
 [5 1 5 5 5]
 [5 5 3 5 5]
 [5 2 5 3 5]]


In [6]:
# Check if any element in a 1D array is non-zero.

import numpy as np
arr = np.array([0, 0, 0, 1, 0])
any_nonzero = np.any(arr)
print(any_nonzero)

True
