In [1]:
import numpy as np

In [5]:
# Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

from scipy.spatial import distance
arr = np.random.randint(1,10,9).reshape(3,3)
print("Array: \n", arr)

euclidean_distance = distance.cdist(arr, arr, 'euclidean')

euclidean_distance        

Array: 
 [[1 8 4]
 [2 8 5]
 [8 9 4]]


array([[0.        , 1.41421356, 7.07106781],
       [1.41421356, 0.        , 6.164414  ],
       [7.07106781, 6.164414  , 0.        ]])

In [23]:
# Write a NumPy program to create a 4x4 array with random values and shift all elements one position downwards.
arr = np.random.randint(1,10,9).reshape(3,3)
print("Array: \n", arr)

temp = arr[-1, :].copy()
arr[1:,:] = arr[:-1,:]
arr[0,:] = temp   
arr

Array: 
 [[9 5 3]
 [1 1 1]
 [4 3 9]]


array([[4, 3, 9],
       [9, 5, 3],
       [1, 1, 1]])