In [1]:
import numpy as np

In [4]:
# Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).

arr = np.random.randint(0,256, size=(300,400,5))

arr

array([[[254,  61,   3,   0,  30],
        [ 77, 145, 152,  93,  15],
        [253, 146, 175, 234,  12],
        ...,
        [ 94,  32, 124, 200,  66],
        [ 14,  81, 234, 147,  42],
        [128, 150, 178, 187,  46]],

       [[180, 177,  91, 240, 101],
        [255, 236, 141,   5,  53],
        [213, 112,  63, 234,  80],
        ...,
        [118, 109,  67, 215,   6],
        [200, 206, 107,  73, 111],
        [132, 114, 155, 183,  71]],

       [[218,  65, 247, 120,  96],
        [134,  81, 240,  44, 206],
        [ 76, 129, 177,  77, 173],
        ...,
        [ 68,  94, 169,  73, 132],
        [230, 128, 200, 141,  37],
        [173, 150, 201, 126,  69]],

       ...,

       [[110,  54, 106, 104,  68],
        [151, 255, 195,  38,  68],
        [109, 235, 203,  61, 189],
        ...,
        [245,  35,  80, 191,   0],
        [200,  26, 116, 239, 248],
        [ 84,  22, 201,  83, 146]],

       [[ 70, 223, 221,  50, 124],
        [213,  55, 187,  82, 146],
        [ 39,  39

In [7]:
# Write a  NumPy program to get the n largest values of an array.
x = np.arange(10)

print("Original Array: \n", x)

np.random.shuffle(x)

print("\n\nArray after shuffling: \n", x)

n = 2
x[np.argsort(x)[-n:]]

Original Array: 
 [0 1 2 3 4 5 6 7 8 9]


Array after shuffling: 
 [8 7 1 5 2 0 9 6 4 3]


array([8, 9])

In [10]:
# Write a  NumPy program to find the closest value (to a given scalar) in an array.
x = np.arange(100)

print("Original Array: \n", x)

value = np.random.uniform(0,100)

print(value)
index = (np.abs(x - value)).argmin()

x[index]

Original Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
69.4616895318626


69

In [22]:
# Write a NumPy program to find the most frequent value in an array.
# Sample Output:
# Original array:
# [6 9 5 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 7 0
# 2 2 6]
# Most frequent value in the above array:
# 5

arr = np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6])

print(arr)

element = np.bincount(arr).argmax()

element

[6 9 5 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 7 0
 2 2 6]


5