In [1]:
import numpy as np

In [2]:
# Write a NumPy program to append a NumPy array to a Python list and print the result.

list1 = []
print("Python List: ", type(list1))

arr = np.array([1,2,3,4,5])
print("Numpy Array: \n", arr, type(arr))

list1.extend(arr.tolist())

print("Numpy Array appended to the list: \n", list1, type(list1))

Python List:  <class 'list'>
Numpy Array: 
 [1 2 3 4 5] <class 'numpy.ndarray'>
Numpy Array appended to the list: 
 [1, 2, 3, 4, 5] <class 'list'>


In [3]:
data_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Data: \n", data_array)
text_file = 'data.txt'

np.savetxt(text_file, data_array, delimiter=" ")

text_file_data = np.loadtxt('data.txt', delimiter=" ")

print("\n\nText File Data: \n",text_file_data)

Original Data: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Text File Data: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
