In [1]:
import numpy as np

In [9]:
# Write a NumPy program that Multiplies each column of a 2D array x of shape (7, 3) by a 1D array y of shape (7,) using broadcasting.

# Create a 2D array x of shape (7, 3)
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18],
              [19, 20, 21]])

# Create a 1D array y of shape (7,)
y = np.array([1, 2, 3, 4, 5, 6, 7])

y[:,None] * x


array([[  1,   2,   3],
       [  8,  10,  12],
       [ 21,  24,  27],
       [ 40,  44,  48],
       [ 65,  70,  75],
       [ 96, 102, 108],
       [133, 140, 147]])

In [16]:
# Write a NumPy program to create a 3D array x of shape (3, 1, 5) and a 2D array y of shape (3, 5). Add x and y using broadcasting.

x = np.array([[[1, 2, 3, 4, 5]],
              [[6, 7, 8, 9, 10]],
              [[11, 12, 13, 14, 15]]])

y = np.array([[10, 20, 30, 40, 50],
              [15, 25, 35, 45, 55],
              [20, 30, 40, 50, 60]])

print(x)
print()
print(y)

x + y[:, np.newaxis]

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]

[[10 20 30 40 50]
 [15 25 35 45 55]
 [20 30 40 50 60]]


array([[[11, 22, 33, 44, 55]],

       [[21, 32, 43, 54, 65]],

       [[31, 42, 53, 64, 75]]])

In [17]:
# Given two 1D arrays a of shape (8,) and b of shape (4,), write a NumPy program to reshape them and perform element-wise addition using broadcasting to get a 2D array of shape (8, 4).
# Create 1D array a of shape (8,)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create 1D array b of shape (4,)
b = np.array([10, 20, 30, 40])

a = a[:, np.newaxis]

a + b

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44],
       [15, 25, 35, 45],
       [16, 26, 36, 46],
       [17, 27, 37, 47],
       [18, 28, 38, 48]])