In [1]:
import numpy as np

In [2]:
# Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.
# Sample output:
# Original array;
# [ 1 3 5 0 -1 -7 0 5]
# Element-wise indication of the sign for all elements of the said array:
# [ 1 1 1 0 -1 -1 0 1]

arr = np.array([1,3,5,0,-1,-7,0,5])
arr[arr < 0] = -1
arr[arr > 0] = 1

arr

array([ 1,  1,  1,  0, -1, -1,  0,  1])

In [3]:
# Write a NumPy program to compute xy, element-wise where x, y are two given arrays.
# Sample output:
# Array1:
# [[1 2]
# [3 4]]
# Array1:
# [[1 2]
# [1 2]]
# Result- x^y:
# [[ 1 4]
# [ 3 16]]

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1,2],[1,2]])
np.power(arr1,arr2)

array([[ 1,  4],
       [ 3, 16]])

In [6]:
# Write a NumPy program to compute the reciprocal for all elements in a given array.
# Sample output:
# Original array:
# [1. 2. 0.2 0.3]
# Reciprocal for all elements of the said array:
# [1. 0.5 5. 3.33333333]

arr = np.array([1,2,0.2,0.3], dtype=float)

print("Original Array: \n", arr)

arr = 1 / arr

arr

Original Array: 
 [1.  2.  0.2 0.3]


array([1.        , 0.5       , 5.        , 3.33333333])

In [8]:
# Write a NumPy program to compute numerical negative value for all elements in a given array.
# Sample output:
# Original array:
# [ 0 1 -1]
# Numerical negative value for all elements of the said array:
# [ 0 -1 1]

arr = np.array([1,0,-1])

print("Original Array: \n", arr)

arr = - arr

arr


Original Array: 
 [ 1  0 -1]


array([-1,  0,  1])

In [9]:
# Write a NumPy program to calculate the difference between neighboring elements, element-wise of a given array.
# Sample output:
# Original array:
# [1 3 5 7 0]
# Difference between neighboring elements, element-wise of the said array.
# [ 2 2 2 -7]

arr = np.array([1,3,5,7,0])

np.diff(arr)

array([ 2,  2,  2, -7])