In [1]:
import numpy as np

In [6]:
# Write a NumPy program to compute the sum of the diagonal element of a given array.

m = np.arange(16).reshape(4, 4)

print(m)

result = np.trace(m)

result

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

In [10]:
# Write a NumPy program to compute the inverse of a given matrix.

print("Original Matrix: \n", m)

np.linalg.inv(m)


Original Matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [12]:
# Write a NumPy program to compute the determinant of an array.

np.linalg.det(m)

-2.9582283945787796e-30