In [3]:
import numpy as np

In [4]:
# Write a NumPy program to add a border (filled with 0's) around an existing array.
array = np.random.randint(1,30,25).reshape(5,5)

print("Original Array: \n", array)

array = np.pad(array, pad_width=1, constant_values=0)

print("Padded Array \n:", array)

Original Array: 
 [[24 11 24  6  6]
 [ 1 25 27 29 18]
 [13 26 23 10 11]
 [20 26  9  5 12]
 [ 7 10 11 17 14]]
Padded Array 
: [[ 0  0  0  0  0  0  0]
 [ 0 24 11 24  6  6  0]
 [ 0  1 25 27 29 18  0]
 [ 0 13 26 23 10 11  0]
 [ 0 20 26  9  5 12  0]
 [ 0  7 10 11 17 14  0]
 [ 0  0  0  0  0  0  0]]


In [5]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
array = np.zeros((8,8))

print("original array: \n", array)

# for even rows
array[::2, 1::2] = 1

# for odd rows
array[1::2, ::2] = 1

print("\nChess board pattern array: \n", array)

original array: 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Chess board pattern array: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [6]:
# Element Check in 1D Array and Intersection Checking between 2 1D array

arr1 = np.array([0,10,20,40,60])
arr2 = np.array([0,30,40])

print(np.in1d(arr1, arr2))

print(np.intersect1d(arr1,arr2))

# Set Difference
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

# Set Exclusive
print(np.setxor1d(arr1,arr2))

# Union
print(np.union1d(arr1, arr2))


[ True False False  True False]
[ 0 40]
[10 20 60]
[30]
[10 20 30 60]
[ 0 10 20 30 40 60]


In [7]:
# Finding the unique elements in the array
arr = np.array([1,2,3,1,2,3,4,2,3])
np.unique(arr)


array([1, 2, 3, 4])

In [9]:
# Write a NumPy program to save a NumPy array to a text file.

arr = np.random.randint(1,20,16).reshape(4,4)

np.savetxt('test.txt', arr)

In [14]:
# Write a NumPy program to create a contiguous flattened array.

print("Original Array: \n", arr)

# flatten returns a array that is flatten
arr2 = arr.flatten()
print("\n\nUsing flatten method: \n", arr2)

Original Array: 
 [[15 14  7 18]
 [ 2 18 13  6]
 [ 5  4 13 10]
 [ 2 15  7  6]]


Using flatten method: 
 [15 14  7 18  2 18 13  6  5  4 13 10  2 15  7  6]


In [26]:
# Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

arr = np.diag([4,5,6,8])

arr

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [27]:
# Write a NumPy program to create a 1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive.

arr = np.linspace(2.5,6.5,30)

print(arr)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [33]:
# Write a NumPy program to change two array axes

arr = np.array([[1,2,3]])

print("original array: \n", arr)



print("With Changed Axes: \n", arr.reshape(3,1))

original array: 
 [[1 2 3]]
With Changed Axes: 
 [[1]
 [2]
 [3]]


In [34]:
# Write a NumPy program to view inputs as arrays with at least one dimension, two dimensions, three dimensions.

x = np.arange(4.0).reshape(2, 2)

print("Original Array: \n", x)

print("\n\nAt least 1 dimension: \n", np.atleast_1d(x))
print("\n\nAt least 2 dimension: \n", np.atleast_2d(x))
print("\n\nAt least 3 dimension: \n", np.atleast_3d(x))

Original Array: 
 [[0. 1.]
 [2. 3.]]


At least 1 dimension: 
 [[0. 1.]
 [2. 3.]]


At least 2 dimension: 
 [[0. 1.]
 [2. 3.]]


At least 3 dimension: 
 [[[0.]
  [1.]]

 [[2.]
  [3.]]]


In [37]:
# Write a  NumPy program to insert a new axis within a 2-D array.
arr = np.random.randint(1,4,4).reshape(2,2)

print("Original Array: \n", arr)

arr = arr.reshape(2,1,2)

print("New Array with additional Axes: \n", arr)

Original Array: 
 [[1 2]
 [1 2]]
New Array with additional Axes: 
 [[[1 2]]

 [[1 2]]]


In [44]:
# Write a NumPy program to concatenate two 2-dimensional arrays.
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print("Array 1: \n", arr1)
print("\nArray 2: \n", arr2)

# Row wise
arr3 = np.concatenate((arr1, arr2), 0)

# Column wise
arr4 = np.concatenate((arr1, arr2), 1)

print("\nAppended Array: \n",arr3)
print("\nAppended Array: \n",arr4)

Array 1: 
 [[1 2 3]
 [4 5 6]]

Array 2: 
 [[ 7  8  9]
 [10 11 12]]

Appended Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Appended Array: 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [48]:
# Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.

arr = np.random.randint(1,100,14)

print("Original Array: \n", arr)

# in this the index from which you want to split are given
np.split(arr, [2,6])

Original Array: 
 [57 44 52 55 15 38  4 54 11 48 44 64 42 20]


[array([57, 44]),
 array([52, 55, 15, 38]),
 array([ 4, 54, 11, 48, 44, 64, 42, 20])]

In [53]:
arr = np.linspace(0.09,0.9,10)

arr

array([0.09, 0.18, 0.27, 0.36, 0.45, 0.54, 0.63, 0.72, 0.81, 0.9 ])

In [64]:
arr = np.arange(1,100)

arr1 = arr[(arr % 3 == 0) | (arr % 5 == 0)]

arr1.sum()

2318

In [76]:
# Write a NumPy program to create and display every element of a NumPy array.

arr = np.random.randint(1,100,16).reshape(4,4)

# normal Method
for row in range(len(arr)):
    for col in range (len(arr)):
        print(arr[row][col], end=" ")

print()       
# using diter method
for ele in np.nditer(arr):
    print(ele, end=" ")

3 79 91 88 33 6 1 69 73 62 95 88 49 83 92 98 
3 79 91 88 33 6 1 69 73 62 95 88 49 83 92 98 

In [78]:
# Write a NumPy program to create a 5x5x5 cube of 1's.

arr = np.ones((5,5,5))

arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [82]:
arr = np.arange(0,12).reshape(3,4)

print("Original Array: \n", arr)

print("\n\nArray with 3 Multipplied: \n", arr * 3)

print("\n\nArray with 3 Multipplied: \n", arr ** 3)

Original Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array with 3 Multipplied: 
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


Array with 3 Multipplied: 
 [[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]


In [89]:
# Write a NumPy program to convert a NumPy array into a Python list structure.

arr = np.random.randint(1,100,16).reshape(4,4)

print(type(arr))

py_list = arr.tolist()

print(type(py_list))    

<class 'numpy.ndarray'>
<class 'list'>


In [94]:
# Write a NumPy program to convert a NumPy array of floating values to a numpy array of integer values.

arr = np.array([[ 12.,12.51],[ 2.34,7.98],[ 25.23,36.5 ]])

print(arr)

print(arr.astype(int))

[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
[[12 12]
 [ 2  7]
 [25 36]]


In [96]:
# Write a NumPy program to replace all elements of  NumPy array that are greater than the specified array.

arr = np.random.normal(1,100,16)

arr[arr < 0] = 0

arr

array([  0.        ,  18.0186292 ,   0.        , 143.77187313,
         0.        ,   0.        ,  40.50532596,  42.59158527,
         0.        , 115.73009149,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   4.05202475])

In [113]:
# Write a  NumPy program to remove all rows in a NumPy array that contain non-numeric values.
x = np.array([[1, 2, 3], [4, 5, np.nan], [7, 8, 9], [True, False, True]])

x_cleaned = x[~np.isnan(x)]

x_cleaned

array([1., 2., 3., 4., 5., 7., 8., 9., 1., 0., 1.])

In [118]:
# Write a  NumPy program to count the frequency of distinct values in a NumPy array.

a = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

array, count = np.unique(a, return_counts=True)

np.asarray((array, count))

array([[10, 20, 30, 40, 50],
       [ 3,  4,  2,  2,  1]], dtype=int64)

In [125]:
# Write a  NumPy program to divide each row by a vector element.
x = np.array([[20, 20, 20], [30, 30, 30], [40, 40, 40]])
print(x)

v = np.array([20, 30, 40])
print(v)

x / v[:, None]

[[20 20 20]
 [30 30 30]
 [40 40 40]]
[20 30 40]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
# Write a NumPy program to access the last two columns of a multidimensional column.

arra = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arra)

print("\n\n", arra[:,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 [[2 3]
 [5 6]
 [8 9]]


In [138]:
# Write a NumPy program to find the position of the index of a specified value ranked higher than an existing value in a NumPy array.
arr = np.array([1,0,2,3,0,9,4,5,6,7,8])
np.argmax(arr)

5

In [141]:
arr = np.array([1,0,2,3,0,9,4,5,6,7]).reshape(2,5)
arr
np.argmax(arr)

5

In [143]:
# Write a  NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

# The p variable has a shape of (3, 3), while q only has a shape of 3.
# Creating a NumPy array 'p' with 3x3 elements
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]])

# Creating another NumPy array 'q' with 1x3 elements
q = np.array([10, 11, 12])

p + q

array([[10, 11, 12],
       [11, 13, 15],
       [14, 16, 18]])

In [144]:
# Write a NumPy program to broadcast on different shapes of arrays where a(,3) + b(3).

p = np.array([[0],
              [10],
              [20]])

# Creating another NumPy array 'q' with 1x3 elements
q = np.array([10, 11, 12])

p + q

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [145]:
# Write a NumPy program to rearrange array dimensions.

arr = np.arange(20).reshape(4,5)

print("Original Array: \n", arr)

print("\n\n Rearranged Array: \n", arr.T)

Original Array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


 Rearranged Array: 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [150]:
# Creating a 3x3 NumPy array 'x' with elements from 0 to 8 using np.arange() and reshaping it
arr1 = np.arange(9).reshape(3, 3)

# Creating another 3x3 NumPy array 'y' by multiplying each element of 'x' by 3
arr2 = x * 3

print(arr1)
print()
print(arr2)
print()
arr3 = np.hstack((arr1,arr2))
print(arr3)

print()
arr4 = np.vstack((arr1,arr2))
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 60  60  60]
 [ 90  90  90]
 [120 120 120]]

[[  0   1   2  60  60  60]
 [  3   4   5  90  90  90]
 [  6   7   8 120 120 120]]

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [ 60  60  60]
 [ 90  90  90]
 [120 120 120]]


In [154]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

# Stackig 1 D arrays as columns
print(np.column_stack((arr1,arr2)))
print() 

# Stackig 1 D arrays as row
print(np.row_stack((arr1,arr2)))

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]


In [163]:
arr = np.arange(16).reshape(4,1,4)

print("Original Array: \n", arr)
print()

# Splittng the array vertically
print(np.vsplit(arr,2))

# splitting the array dimensionally
print(np.dsplit(arr,2))

Original Array: 
 [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]]

[array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]]), array([[[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]]])]
[array([[[ 0,  1]],

       [[ 4,  5]],

       [[ 8,  9]],

       [[12, 13]]]), array([[[ 2,  3]],

       [[ 6,  7]],

       [[10, 11]],

       [[14, 15]]])]


In [166]:
# Write a NumPy program to copy data from a given array to another array.

arr = np.array([1,2,3,4,5,6])

arr_copy = arr.copy()
arr[0] = 10
arr_copy

array([1, 2, 3, 4, 5, 6])

In [173]:
# Write a  NumPy program to get the row numbers in a given array where at least one item is larger than a specified value.

arr = np.arange(36).reshape(4,9)

print("Original Array: \n", arr)

np.where(np.any(arr> 10, axis = 1))

Original Array: 
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


(array([1, 2, 3], dtype=int64),)

In [179]:
# Write a NumPy program to extract the upper triangular part of a NumPy matrix.
arr = np.arange(18).reshape(6,3)

print("Original Array: \n", arr)

print('Upper Triangle: \n', arr[np.triu_indices(3)])

Original Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Upper Triangle: 
 [0 1 2 4 5 8]


In [183]:
# Write a NumPy program to rearrange columns of a given numpy 2D array using given index positions.

array1 = np.array([[11, 22, 33, 44, 55],
                    [66, 77, 88, 99, 100]])

print("Original Array: \n", array1)

i = [1,3,0,4,2]

result = array1[:, i]

print("\n\nNew array: \n",result)

Original Array: 
 [[ 11  22  33  44  55]
 [ 66  77  88  99 100]]


New array: 
 [[ 22  44  11  55  33]
 [ 77  99  66 100  88]]


In [198]:
# Write a NumPy program to combine the last element with the first element of two given ndarray with different shapes.

arr1 = np.array(['PHP', 'JS', 'C++'])
arr2 = np.array(['Python', 'C#', 'Numpy'])
f_arr = arr1[0:-1]
s_arr = arr1[-1] + arr2[0]
t_arr = arr2[1:]

np.concatenate((f_arr, [s_arr], t_arr))



array(['PHP', 'JS', 'C++Python', 'C#', 'Numpy'], dtype='<U9')

In [207]:
# Write a  NumPy program to search the index of a given array in another given array.

np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

test_array = np.array([4, 5, 6])

result = np.where((test_array == np_array))[0]

result

array([1, 1, 1], dtype=int64)

In [217]:
arra = np.array([[1, 1, 0],
                 [0, 0, 0],
                 [0, 2, 3],
                 [0, 0, 0],
                 [0, -1, 1],
                 [0, 0, 0]])

result = np.unique(arra, axis = 0)


array([ 0, -1,  1,  0,  0,  0,  0,  2,  3,  1,  1,  0])

In [222]:
array = np.array([1,2,3,4,5,6,7,8])

print("Original Array: \n",array)

zero_array = np.zeros(len(array) * 3)

zero_array[::3] = array

print(zero_array[:-2])

Original Array: 
 [1 2 3 4 5 6 7 8]
[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5. 0. 0. 6. 0. 0. 7. 0. 0. 8.]


In [232]:
nums = np.random.randint(0, 4, (6, 3))

nums

array([[2, 1, 1],
       [0, 1, 1],
       [3, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 2, 2]])