In [1]:
import numpy as np

In [2]:
# Write a NumPy program that uses np.maximum.reduce to find the maximum element along a specified axis of a 2D array.

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("The Array: \n", array_2d)

max_along_zero = np.maximum.reduce(array_2d, axis=0)
max_along_one = np.maximum.reduce(array_2d, axis=1)

print("The Maximum Along Zero Axis: \n", max_along_zero)
print("The Minimum Along One Axis: \n", max_along_one)

The Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Maximum Along Zero Axis: 
 [7 8 9]
The Minimum Along One Axis: 
 [3 6 9]


In [6]:
# Write a NumPy program that uses np.logical_and to combine two boolean arrays based on element-wise logical AND operation.

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

print("Array 1: \n", arr1)
print("\n\nArray 2: \n", arr2)

print("\nLogical AND: \n", np.logical_and(arr1, arr2))
print("\nLogical OR: \n", np.logical_or(arr1, arr2))

Array 1: 
 [ True  True False False]


Array 2: 
 [ True False  True False]

Logical AND: 
 [ True False False False]

Logical OR: 
 [ True  True  True False]
