In [3]:
import numpy as np
import numpy.ma as ma

In [7]:
# Write a NumPy program that creates a masked array and checks if any masked elements are present.
arr = np.random.randint(1,10,20).reshape(4,5)

print("Original Array: \n", arr)

condition = arr < 5

masked_array = ma.masked_array(arr, mask = condition)

has_masked_value = masked_array.mask.any()
print("\nIs There any Values? ", has_masked_value)

print("\nMasked Array: \n", masked_array)



Original Array: 
 [[9 9 4 7 7]
 [7 5 9 5 5]
 [9 3 7 3 7]
 [4 3 1 6 6]]

Is There any Values?  True

Masked Array: 
 [[9 9 -- 7 7]
 [7 5 9 5 5]
 [9 -- 7 -- 7]
 [-- -- -- 6 6]]


In [8]:
# Write a NumPy program that creates a masked array and applies a mathematical function (e.g., sin, cos) only to the unmasked elements.
arr = np.random.randint(1,10,20).reshape(4,5)

print("Original Array: \n", arr)

condition = arr < 5

masked_array = ma.masked_array(arr, mask = condition)

print("\nMasked Array: \n", masked_array)

result_array = ma.sin(masked_array)
print("\n Result Array after function Applied on the unmasked elements: \n", result_array)


Original Array: 
 [[5 1 8 5 5]
 [7 4 6 7 6]
 [2 8 4 7 1]
 [7 5 7 4 4]]

Masked Array: 
 [[5 -- 8 5 5]
 [7 -- 6 7 6]
 [-- 8 -- 7 --]
 [7 5 7 -- --]]

 Result Array after function Applied on the unmasked elements: 
 [[-0.9589242746631385 -- 0.9893582466233818 -0.9589242746631385
  -0.9589242746631385]
 [0.6569865987187891 -- -0.27941549819892586 0.6569865987187891
  -0.27941549819892586]
 [-- 0.9893582466233818 -- 0.6569865987187891 --]
 [0.6569865987187891 -0.9589242746631385 0.6569865987187891 -- --]]
